name: Python CI Test

on: [push]

jobs:
  test-logic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This "downloads" your code onto the runner

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Pytest
        run: pip install pytest    # Install the tool that runs the tests

      - name: Run Tests
        run: pytest test_calculator.py  # Run the actual test
